# DO NOT USE THIS CONFIGURATION IN PRODUCTION!
# Please visit https://garagehq.deuxfleurs.fr/documentation/quick-start/ for more information.
metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "sqlite"

replication_factor = 1

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"
rpc_secret = "c860837cfe1d253e4b5832ad5346f3860b38ba738b581ed798c9a724eb3e4bc1"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"
root_domain = ".s3.garage.localhost"

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".web.garage.localhost"
index = "index.html"

[k2v_api]
api_bind_addr = "[::]:3904"

[admin]
api_bind_addr = "[::]:3903"
admin_token = "3gyJMZlfhtBmKtCgioxsN7JV3oQeC3VjyzaogD6uV+o="
metrics_token = "CVMglnJJOCF6XKhauDsghrdMXNfepCyvKhd8UdpvL2o="
