# Example compose file for local development and testing
# DO NOT USE IN PRODUCTION!
# DO NOT USE DEFAULT CREDENTIALS IN PRODUCTION!

# It is required to have the object storage service running before starting this stack.
name: CivicSage Stack
services:
  civicsage:
    build: ..
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/example
      SPRING_DATASOURCE_USERNAME: example
      SPRING_DATASOURCE_PASSWORD: example
      SECURITY_ALLOWED-ORIGINS: localhost:8080
      LOGGING_LEVEL_DE_UOL_PGDOENER_CIVICSAGE: DEBUG
      CIVICSAGE_EMBEDDING_MODEL_CONTEXTLENGTH: 256
      SPRING_AI_OPENAI_BASEURL: http://host.docker.internal:12434/engines
      S3_URL: http://garage:3900
      S3_BUCKET_NAME: civicsage-bucket
      S3_REGION: garage
    env_file:
      - path: civicsage.env
        required: false
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      db:
        condition: service_healthy
      garage:
        condition: service_started
  db:
    image: pgvector/pgvector:pg17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=example
      - PGUSER=example
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      start_period: 5s

  garage:
    image: dxflrs/garage:v2.0.0
    container_name: garaged
    ports:
      - "3900:3900"
      - "3901:3901"
      - "3902:3902"
      - "3903:3903"
    volumes:
      - ./objectstorage/garage.toml:/etc/garage.toml
      - ./objectstorage/meta:/var/lib/garage/meta
      - ./objectstorage/data:/var/lib/garage/data

  garage_config:
    image: docker:cli
    container_name: garage_config
    depends_on:
      garage:
        condition: service_started
    volumes:
      - ./objectstorage/scripts:/scripts
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: [ "/bin/sh", "-c" ]
    command: >
      "
      echo 'Waiting for Garage service...';
      until nc -z garage 3900; do
        echo 'Garage not available yet. Sleeping...';
        sleep 2;
      done;
      echo 'Garage is available. Running initialization...';
      /scripts/configure.sh;
      "
