name: ObjectStorage
services:
  garage:
    image: dxflrs/garage:v2.0.0
    container_name: garaged
    ports:
      - "3900:3900"
      - "3901:3901"
      - "3902:3902"
      - "3903:3903"
    volumes:
      - ./objectstorage/garage.toml:/etc/garage.toml
      - ./objectstorage/meta:/var/lib/garage/meta
      - ./objectstorage/data:/var/lib/garage/data

  garage_config:
    image: docker:cli
    depends_on:
      garage:
        condition: service_started
    volumes:
      - ./objectstorage/scripts:/scripts
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: [ "/bin/sh", "-c" ]
    command: >
      "
      echo 'Waiting for Garage service...';
      until nc -z garage 3900; do
        echo 'Garage not available yet. Sleeping...';
        sleep 2;
      done;
      echo 'Garage is available. Running initialization...';
      /scripts/configure.sh;
      "
